### ISSUE TITLE
Consider adding project to boardgame.io projects list

### ISSUE THREAD

**Issue by delucis** [vyang1222/online-coup#1]
Hi @vyang1222, I’m one of the maintainers of the boardgame.io framework. I hope you’ve enjoyed using it! We have a page documenting interesting projects built using the library here: https://boardgame.io/documentation/#/notable_projects

If you are interested in adding your game to the list, we would be happy to include it so others can learn from your implementation and enjoy the game.

Thanks!
Chris.

**Comment by vyang1222** [comment]
Hi @delucis, thanks for reaching out! I'm interested in adding my game to the list. Please let me know if you need any additional information about my game.

Thanks,
Victor Yang

**Comment by delucis** [comment]
Hi Victor — great!

If you like, you can add your game yourself by opening a pull request. I’d be happy to walk you through that if you have any questions. You can head over to [the source file on GitHub](https://github.com/boardgameio/boardgame.io/blob/master/docs/documentation/notable_projects.md) and click the pencil “edit” button at the top right to get started.

**Comment by vyang1222** [comment]
Okay, I opened a pull request. I wasn't sure about the alphabetical order aspect for the list, so I just added my game to the end. Please let me know if you need anything else from me.
